export { login, register } from './login'
export type { LoginResult, RegisterDTO } from './login'
export { default as sysUserApi, addSysUser } from './sysUser'
export { default as sysUserRoleApi } from './sysUserRole'
export { default as sysRoleApi } from './sysRole'
export { default as sysRoleMenuApi } from './sysRoleMenu'
export { default as sysMenuApi } from './sysMenu'
export { default as sysMajorApi } from './sysMajor'
export { default as sysDepartmentApi } from './sysDepartment'
export { default as sysDataPermissionApi } from './sysDataPermission'
export { default as sysCollegeApi } from './sysCollege'
export { default as sysClubApi } from './sysClub'
export { default as noticeReadRecordApi } from './noticeReadRecord'
export { default as noticeInfoApi } from './noticeInfo'
export { default as noticeCategoryApi } from './noticeCategory'
export { default as clubStatisticsApi } from './clubStatistics'
export { default as activitySignApi } from './activitySign'
export { default as activityCategoryApi } from './activityCategory'
export { default as activityApproveFlowApi } from './activityApproveFlow'
export { default as activityApplyApi } from './activityApply'
